Splits skill children between skills and activities
France-ioi/AlgoreaFrontend pull request #1241
Opened 2022-12-21 15:38 UTC by Iloveall

## Description

Fixes #...

## Notes (out of scope, known isues, hints for reviewing code, ...)  (optional)

...

## Test cases

- [ ] Case 1:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/branch/feature/split-skill-children-edition-between-skills-and-activities/en/skills/by-id/1428191708697704090;path=;attempId=0)
  3. And I click on switch edit content button
  4. Then I see "Sub-skills" and "Activities to learn or reinforce this skill" sections
  5. Then I type "New Skill" under "Sub-skills" section and I see Skill type button
  6. Then I click on "A New Skill" button
  7. Then I see "New Skill" in "Sub-skills" section

- [ ] Case 2:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/branch/feature/split-skill-children-edition-between-skills-and-activities/en/skills/by-id/1428191708697704090;path=;attempId=0)
  3. And I click on switch edit content button
  4. Then I see "Sub-skills" and "Activities to learn or reinforce this skill" sections
  5. Then I type "New Chapter" under "Activities to learn or reinforce this skill" section 
  6. And I see Chapter, Task, Course type buttons
  7. Then I click on "Chapter" button
  8. Then I see "New Chapter" in "Activities to learn or reinforce this skill" section

2022-12-23 10:09 UTC, smadbe requested changes

2022-12-23 16:26 UTC, Iloveall commented on src/app/modules/item/components/item-children-edit-list/item-children-edit-list.component.ts
> +    this.childrenChanges.emit(this.data);
Fixed

FYI: Seems like the primeng table does the same modification of data when order or weight changed. Then I wondered how many times ng changes, ng check content, ng check view calls - the result is the same. For example:

This code won’t trigger ng changes in current component:

`orderChanged(): void {
    this.childrenChanges.emit(this.data);
  }`

2022-12-23 17:45 UTC, Iloveall commented on src/app/modules/item/components/item-children-edit/item-children-edit.component.ts
> +      this.skills = data.filter(item => item.isVisible && isASkill(item));
Fixed.

Tested locally through modifying permissions in array:

<img width="1174" alt="Screenshot at Dec 23 19-41-20" src="https://user-images.githubusercontent.com/7044736/209380806-1d5a978f-f05c-4086-96c8-42aa90a88005.png">

2023-01-03 15:11 UTC, smadbe approved these changes
looks good

2023-01-03 16:07 UTC, merged