hide automatically the left menu on mobile (narrow) when we select a task in the left menu
France-ioi/AlgoreaFrontend pull request #1376
Opened 2023-05-31 16:33 UTC by smadbe

## Description

Hide automatically the left menu on mobile (narrow) when we select a task in the left menu

## Test cases

- use mobile layout
- show the left menu  
- the left menu auto-hide when navigating to a task

2023-05-31 16:47 UTC, Iloveall commented
But why only tasks? Wouldn't be useful to close by click on any item (non chapter) ?

2023-06-01 09:51 UTC, smadbe commented
> But why only tasks? Wouldn't be useful to close by click on any item (non chapter) ?

Non chapters are only tasks and skills. Skills behave more as chapter. The feature has been validated only for tasks.

2023-06-01 10:26 UTC, Iloveall requested changes

2023-06-01 11:26 UTC, smadbe commented on src/app/shared/services/layout.service.ts
> +    switchMap(values => concat(this.manualMenuToggle$).pipe(
ahah, right 👍

2023-06-01 11:37 UTC, Iloveall approved these changes

2023-06-01 11:38 UTC, merged