Fixes position of bubbles in thread message
France-ioi/AlgoreaFrontend pull request #1498
Opened 2023-09-29 10:04 UTC by Iloveall

## Description

Fixes #1494

## Notes (out of scope, known isues, hints for reviewing code, ...)  (optional)

...

## Test cases

- [ ] Case 1:
  1. Given I am the demouser
  2. When I go to [this page](https://dev.algorea.org/branch/feature/forum-open-close-thread-implementation/en/a/6379723280369399253;p=4702,1625159049301502151,5207993233955027100;pa=0/forum/others)
  3. And I click on open the thread
  4. Then I see the colours are correct

- [ ] Case 2:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/branch/feature/forum-open-close-thread-implementation/en/a/6379723280369399253;p=7528142386663912287,7523720120450464843;a=0/forum/others?watchedGroupId=752024252804317630&watchUser=1)
  3. And I click on open the thread
  4. Then I see the colours are correct

2023-09-29 14:42 UTC, smadbe requested changes
> Then I see the colours are correct

From Slack: 
> when participant><current-user: you could stick with the observation-mode color for participant, white for the others, so could be blue for oneself
when participant=current_user: I would say white for others and blue for oneself

In the first scenario (as the demo user): if I click on the thread by "arbonenfant": arbonenfant's bubbles are in white while I would expect the observation-mode color (yellow/pink) for them.

2023-09-29 14:43 UTC, smadbe commented
More globally I only see 2 colors: blue and white. While I would expect 3. 
![Screenshot 2023-09-29 at 16 43 32](https://github.com/France-ioi/AlgoreaFrontend/assets/1053150/be9e043f-7a10-4619-a251-99a7d6e865ef)

2023-10-02 07:13 UTC, Iloveall commented
I've cre

> More globally I only see 2 colors: blue and white. While I would expect 3. ![Screenshot 2023-09-29 at 16 43 32](https://user-images.githubusercontent.com/1053150/271638193-be9e043f-7a10-4619-a251-99a7d6e865ef.png)

I've create [issue](https://github.com/France-ioi/AlgoreaFrontend/issues/1499) for this

2023-10-02 08:03 UTC, smadbe approved these changes

2023-10-02 09:31 UTC, merged