Move observation to ngrx store
France-ioi/AlgoreaFrontend pull request #1625
Opened 2024-01-22 16:04 UTC by smadbe

## Description

Move observation (and router to support observation) to ngrx store 

## Test cases

- [ ] Case 1:
  1. Given I am the usual user
  2. I open the dev tools
  3. When I go to [the home page](https://dev.algorea.org/branch/rootstore/en/a/home;pa=0)
  4. And I click on "ALGOREA ADVENTURE "
  5. Then if I move back and forth in the store history, I navigate from one page to the other 

- [ ] Case 2:
  1. Given I am the usual user
  2. I open the dev tools
  3. When I [start observation through url](https://dev.algorea.org/branch/rootstore/en/a/home;pa=0?watchedGroupId=672913018859223173&watchUser=0)
  4. I see the group name has been fetched and observation has started with the right name in the bar
  5. And I close the observation mode via the top bar
  6. And I am not in observation mode anymore

- [ ] Case 3:
  1. Given I am the usual user
  3. When I [start observing a group that does not exist](https://dev.algorea.org/branch/rootstore/en/a/home;pa=0?watchedGroupId=404&watchUser=0)
  4. I see the error message
  7. and closer the modal continues without observation

- [ ] Case 4:
  1. Given I am the usual user
  3. When I [start observing a group that I can see but not watch](https://dev.algorea.org/branch/rootstore/en/a/home;pa=0?watchedGroupId=52767158366271444&watchUser=0)
  4. I see the error message
  5. and closer the modal continues without observation

- [ ] Case 5:
  1. Given I am the usual user
  2. And I open dev tool
  3. When I [go the page of a group I can watch](https://dev.algorea.org/branch/rootstore/en/groups/by-id/672913018859223173;p=52767158366271444)
  4. and I click on the eye in the top bar
  5. I see I am in observation mode
  8. I see in the network request that no request to get the group name has been done
  9. I go to "content" in the left menu
  10. I close the observation mode through the left menu
  11. And it leaves observation

- [ ] Case 6:
  1. Given I am the usual user
  3. When I [go the page of a user I can watch](https://dev.algorea.org/branch/rootstore/en/groups/users/752024252804317630)
  4. and I click on the eye in the header
  5. I see I am in observation mode
  6. And I reclick on the eye
  7. And I leave the observation mode

2024-01-23 13:50 UTC, Iloveall requested changes
Huge PR 💪

2024-01-23 13:50 UTC, Iloveall commented on src/app/items/item-by-id.component.html
> +            <ng-container *ngIf="(!isObserving$ && (itemData.item.permissions | allowsViewingContent)) || (itemData.item.permissions | allowsWatchingResults) ; else unallowed">
*ngrxLet="isObserving$ as isObserving": is not using isObserving here

2024-01-23 13:50 UTC, Iloveall commented on src/app/items/item-by-id.component.html
> +                  *ngIf="isObserving$"
Same here

2024-01-23 13:50 UTC, Iloveall commented on src/app/items/item-by-id.component.html
> +                  *ngIf="!isObserving$"
Same here

2024-01-23 13:50 UTC, Iloveall commented on src/app/items/item-by-id.component.html
> +              <p class="not-allow-caption" *ngIf="isObserving$" i18n>
Same here

2024-01-23 13:50 UTC, Iloveall commented on src/app/items/item-by-id.component.html
> +              <p class="not-allow-caption" *ngIf="!isObserving$" i18n>
Same here

2024-01-23 20:18 UTC, smadbe commented
Thanks for spotting this error 👍 . Fixed

2024-01-24 13:32 UTC, Iloveall approved these changes

2024-01-24 19:30 UTC, merged