Translation of group module
France-ioi/AlgoreaFrontend pull request #291
Opened 2021-01-06 10:48 UTC by AyeRlS

The group module has been marked for translation,

2021-01-06 14:00 UTC, smadbe requested changes

2021-01-07 08:56 UTC, AyeRlS commented on src/app/modules/group/components/group-invite-users/group-invite-users.component.ts
> +        detail: $localize`${successInvites.join(', ')}`,
Fixed

2021-01-07 08:56 UTC, AyeRlS commented on src/app/modules/group/components/group-invite-users/group-invite-users.component.html
> +<alg-section-paragraph icon="fa fa-user-plus" i18n-label i18n-label label="Invite users" [collapsible]="true">
Fixed

2021-01-07 08:56 UTC, AyeRlS commented on src/app/modules/group/components/group-composition-filter/group-composition-filter.component.ts
> +    if (index < 0 || index >= typeFilters.length) throw Error($localize`invalid value for type filter`);
Fixed

2021-01-07 13:48 UTC, smadbe requested changes
Looks like some strings are missing, check everything carefully.

2021-01-07 13:48 UTC, smadbe commented on src/app/modules/group/components/group-join-by-code/group-join-by-code.component.html
>          it will be disabled in {{ groupExt.durationBeforeCodeExpiration! | toMin | number:'1.0-0' }} minutes.
And this one? And the 2 lines below?

2021-01-07 13:48 UTC, smadbe commented on src/app/modules/group/components/joined-group-list/joined-group-list.component.html
>          <th pSortableColumn="member_since">Joined On <p-sortIcon field="member_since"></p-sortIcon></th>
And this one?

2021-01-08 12:04 UTC, AyeRlS commented on src/app/modules/group/components/joined-group-list/joined-group-list.component.html
>          <th pSortableColumn="member_since">Joined On <p-sortIcon field="member_since"></p-sortIcon></th>
Fixed

2021-01-08 12:04 UTC, AyeRlS commented on src/app/modules/group/components/group-join-by-code/group-join-by-code.component.html
>          it will be disabled in {{ groupExt.durationBeforeCodeExpiration! | toMin | number:'1.0-0' }} minutes.
Fixed

2021-01-08 15:51 UTC, smadbe reviewed
Ok, I'll do the translations.

2021-01-08 16:54 UTC, smadbe approved these changes
You can merge. Resolve **carefully** the conflicts first for the xlf files.

2021-01-12 13:23 UTC, smadbe requested changes

2021-01-12 13:23 UTC, smadbe commented on src/locale/messages.fr.xlf
> +      <target state="translated"> Tous sélectionner </target>
tout

2021-01-12 17:49 UTC, smadbe approved these changes

2021-01-13 10:51 UTC, merged