Item edit 2
France-ioi/AlgoreaFrontend pull request #316
Opened 2021-02-12 13:44 UTC by gustavomorenomena

Add "Score & Validation" and "Display" sections to global parameters tab

2021-02-12 17:02 UTC, smadbe requested changes

2021-02-12 17:02 UTC, smadbe commented on src/app/modules/shared-components/components/selection/selection.component.ts
> +          if (index !== -1) this.selected = index;
"else" again ?

2021-02-12 17:02 UTC, smadbe commented on src/app/modules/shared-components/components/selection/selection.component.ts
> +    } else {
also in case `this.parentForm.get(this.name)` is null ? Maybe be a confusing case for the developer.

2021-02-22 17:41 UTC, gustavomorenomena commented on src/app/modules/item/http-services/get-item-by-id.service.ts
> +  validation_type: string,
fixed

2021-02-22 17:41 UTC, gustavomorenomena commented on src/app/modules/item/http-services/get-item-by-id.service.ts
> +  full_screen: string,
fixed

2021-02-22 17:41 UTC, gustavomorenomena commented on src/app/modules/item/http-services/update-item.service.ts
> +  validation_type?: string,
fixed

2021-02-22 17:42 UTC, gustavomorenomena commented on src/app/modules/item/http-services/update-item.service.ts
> +  full_screen?: string,
fixed

2021-02-22 17:42 UTC, gustavomorenomena commented on src/app/modules/item/pages/item-edit-advanced-parameters/item-edit-advanced-parameters.component.html
> +      <span class="form-item-label" i18n>Display group code header (not implemented)</span>
fixed

2021-02-22 18:14 UTC, gustavomorenomena commented on src/app/modules/shared-components/components/selection/selection.component.ts
> +    if (Object.prototype.hasOwnProperty.call(simpleChanges, 'parentForm') && this.parentForm && this.items.length) {
fixed

2021-02-22 18:15 UTC, gustavomorenomena commented on src/app/modules/shared-components/components/selection/selection.component.ts
> +        this.subscriptions.push(formControl.valueChanges.subscribe(value => {
fixed

2021-02-22 18:17 UTC, gustavomorenomena commented on src/app/modules/shared-components/components/selection/selection.component.ts
> +          if (index !== -1) this.selected = index;
fixed

2021-02-23 13:03 UTC, smadbe commented on src/app/modules/shared-components/components/selection/selection.component.ts
> +    } else {
not answered

2021-02-23 13:03 UTC, smadbe commented on src/app/modules/item/pages/item-edit/item-edit.component.ts
> +      no_score: item.no_score || false,
not answered/adressed

2021-02-26 07:48 UTC, smadbe requested changes

2021-02-26 07:48 UTC, smadbe commented on src/app/modules/shared-components/components/selection/selection.component.ts
> +  private formControlChangesSubscription: Subscription | undefined;
```suggestion
  private formControlChangesSubscription?: Subscription;
```

2021-02-26 07:48 UTC, smadbe commented on src/app/modules/shared-components/components/selection/selection.component.ts
> +        if (this.formControlChangesSubscription) this.formControlChangesSubscription.unsubscribe();
```suggestion
        this.formControlChangesSubscription?.unsubscribe();
```

2021-02-26 07:48 UTC, smadbe commented on src/app/modules/shared-components/components/selection/selection.component.ts
> +    if (this.formControlChangesSubscription) this.formControlChangesSubscription.unsubscribe();
```suggestion
    this.formControlChangesSubscription?.unsubscribe();
```

2021-02-26 17:05 UTC, smadbe approved these changes
👍  you can merge

2021-03-01 07:11 UTC, merged