Feature/group user list progress
France-ioi/AlgoreaFrontend pull request #477
Opened 2021-06-14 16:21 UTC by Iloveall

Fixes #401

2021-07-05 10:54 UTC, smadbe requested changes
First quick remark: If I go on the progress on the usual user and click on "Empty chapter", I arrive on an error page (while this page is visible by the user), so I assume there is an error in the links somehow (if you think the issue is not related with your implementation, let me know).
![Screenshot 2021-07-05 at 12 52 19](https://user-images.githubusercontent.com/1053150/124460590-d6e00700-dd8f-11eb-867d-763ccaf4cd3f.png)

2021-07-07 14:49 UTC, smadbe requested changes
Only small details to fix.

2021-07-08 10:47 UTC, Iloveall commented on src/app/modules/group/components/group-log-view/group-log-view.component.ts
> +    return columns.filter(item => !item.disabled).map(item => ({
Fixed

2021-07-12 11:03 UTC, smadbe approved these changes
👍 Maybe wait for the other PR to be ready before merging it.

2021-07-12 12:46 UTC, Iloveall commented on src/app/modules/group/components/group-log-view/group-log-view.component.html
> +                {{ rowData.user | userCaption }}
Fixed

2021-07-13 14:39 UTC, merged