Hides pending request and add subgroups panels for none membership
France-ioi/AlgoreaFrontend pull request #478
Opened 2021-06-14 17:05 UTC by Iloveall

Fixes #444

2021-06-16 12:50 UTC, smadbe commented on src/app/modules/group/pages/group-details/group-details.component.html
> +        *ngIf="group.isCurrentUserManager && group?.currentUserCanManage !== 'none'"
I don't think `group` is optional.

2021-06-21 11:35 UTC, Iloveall commented on src/app/modules/group/pages/group-details/group-details.component.html
> +        *ngIf="group.isCurrentUserManager && group?.currentUserCanManage !== 'none'"
Fixed

2021-07-05 10:37 UTC, smadbe requested changes
I forgot in the spec: could you remove the "remove" button as well when the user has "none" level? 
![Screenshot 2021-07-05 at 12 36 28](https://user-images.githubusercontent.com/1053150/124458735-a0a18800-dd8d-11eb-9d8b-fae27b78f634.png)

2021-07-06 12:42 UTC, smadbe approved these changes

2021-07-06 13:41 UTC, merged