Fix removed invisible item children
France-ioi/AlgoreaFrontend pull request #547
Opened 2021-07-20 10:15 UTC by ThomasJuster

Fixes #542

2021-07-23 13:09 UTC, smadbe requested changes

2021-07-23 14:34 UTC, ThomasJuster commented on src/app/modules/item/components/item-children-edit/item-children-edit.component.ts
> +      contentType: typeCategoryOfItem(child as { type: ItemType }),
Fixed

2021-07-23 14:34 UTC, ThomasJuster commented on src/app/modules/item/components/item-children-edit/item-children-edit.component.ts
> +  isVisible: boolean;
Fixed

2021-07-23 14:34 UTC, ThomasJuster commented on src/app/modules/item/helpers/item-permissions.ts
> +}
Fixed

2021-07-23 14:34 UTC, ThomasJuster commented on src/app/modules/item/http-services/get-item-children.service.ts
> +const itemVisibleChildDecoder = D.intersect(baseItemChildDecoder)(
Fixed

2021-07-26 08:10 UTC, ThomasJuster commented
To be tested on item 561969155071897034:
[localhost](http://localhost:4200/#/activities/by-id/561969155071897034;parentAttempId=0;path=4702,1352246428241737349/edit)
[dev.algorea.org](https://dev.algorea.org/branch/fix/removed-invisible-item-children/en/#/activities/by-id/561969155071897034;parentAttempId=0;path=4702,1352246428241737349/edit)

2021-07-27 13:12 UTC, smadbe approved these changes
Everything looks good.

2021-07-27 14:21 UTC, merged