revamp group join by code
France-ioi/AlgoreaFrontend pull request #556
Opened 2021-07-21 16:33 UTC by ThomasJuster

2021-07-27 11:09 UTC, ThomasJuster commented
I added some quick styling that might need a second intervention:
- Usage of `.block-ui` class [here](https://github.com/France-ioi/AlgoreaFrontend/pull/556/files#diff-48d5381ebec6e1b71d2404595ac8808cc044274234d9ede072be07bd5bba98f1R1) and [here](https://github.com/France-ioi/AlgoreaFrontend/pull/556/files#diff-88156bbee312190764fae94f96f5485b9a678d6ff7475720c9c9f56a8b114621R4)
- host styles to make `.block-ui` work as a child [here](https://github.com/France-ioi/AlgoreaFrontend/pull/556/files#diff-a45083ba54fd52b6a656ae92a7fa91b9c0a9372a5559be5b7bfaf0fa624c1420R4-R7) and [here](https://github.com/France-ioi/AlgoreaFrontend/pull/556/files#diff-f4c7504e2f624a3aa39be70aa8eb528972b4390141c75e96bd2b9846bb5bf65cR1-R5)
- All the sass files changes, obviously
- Hack in alg-duration component template to make vertical alignment work [here](https://github.com/France-ioi/AlgoreaFrontend/pull/556/files#diff-9be3cbfcab601936e5535c22f05a5a11cf2682f39423961c98678dd3b17f082fR44)
- Creation of `.block-ui` class [here](https://github.com/France-ioi/AlgoreaFrontend/pull/556/files#diff-b950ba7aa9f8dbe0e6d51ce5e8c55374ef4b5ce670758e0a295ac4c50a50c63a)
- group join by code nested styles [here](https://github.com/France-ioi/AlgoreaFrontend/pull/556/files#diff-6c437fb879e29e28c82b57fdf3d97654ab7d64b583cc2f7d7a8c41e03139d0f3)

2021-07-27 14:22 UTC, smadbe requested changes
Initial UI review. 
1. Unlike what was done before, the expiration is not resetted when code is changed... even when code is removed/recreated which looks strange or when the validity is infinite: 
![Screenshot 2021-07-27 at 15 59 33](https://user-images.githubusercontent.com/1053150/127167867-bbf131d3-c797-4699-9b44-29cca73bceb7.png)
![Screenshot 2021-07-27 at 16 06 47](https://user-images.githubusercontent.com/1053150/127168343-6c59b953-0742-47ac-9cc1-9bac23c375d8.png)
I think the previous behavior is better, so reset the expiration when the code is changed, removed, added.

2. When the custom duration has not changed, the validation button should be greyed out as it has no effect.

3. As the buttons have immediate effect as are not 100% straightforward, it would be useful to display tooltips on hover:
   - refresh code: "Generate a new code and reset expiration."
   - remove code: "Disable code access."
   - infinite: "This code will never expire (reset current expiration)."
   - usable once: "This code will be usable only once (reset current expiration)."
   - custom: "This code will expire after the given duration (reset current expiration)."
   - custom validation: "This code will expire after the given duration (reset current expiration)."

4. It uses hours, minutes and seconds while what was requested is days, hours and minutes!!!

2021-07-27 14:33 UTC, smadbe requested changes
5. When the data is: 
```... code_lifetime":0,"code_expires_at":"2021-07-27T16:20:00Z","....``` (I am now around 2021-07-27 14:33:13)
I get 
![Screenshot 2021-07-27 at 16 31 57](https://user-images.githubusercontent.com/1053150/127172637-5a071992-fe86-4e4f-8a49-172f2965d2ea.png)

Okay if the expiration is in 2hours and the code has a validity of 0min, I see why we have this message... but let's consider we may have such data in the db as some legacy data is "buggy". In this case, let's say, we should only display "This code will be disabled in 102 minutes."

2021-07-27 16:43 UTC, ThomasJuster commented
Fixed

2021-08-03 09:15 UTC, smadbe requested changes
Oh again, I did the review the review but I switched before submitting it. Oh sorry, it would have been nice to complete it before your holidays.

2021-08-24 09:13 UTC, ThomasJuster commented on src/app/modules/group/components/group-join-by-code/group-join-by-code.component.ts
> +  codeLifetimeOptions = [
Fixed

2021-08-24 09:22 UTC, ThomasJuster commented on src/app/modules/group/components/group-join-by-code/group-join-by-code.component.ts
> +    if (this.codeAdditions.hasCodeNotSet || isSameCodeLifetime(this.group.codeLifetime, newCodeLifetime)) return;
Fixed

2021-08-24 09:25 UTC, ThomasJuster commented on src/app/modules/group/components/group-join-by-code/group-join-by-code.component.ts
> +          (expiresAt === null ? of(undefined) : this.groupActionsService.updateGroup(groupId, { code_expires_at: null }))
Fixed

2021-08-24 09:27 UTC, ThomasJuster commented on src/app/modules/group/components/group-join-by-code/group-join-by-code.component.ts
> +    if (codeLifetime instanceof Duration) {
yes because it also treats the undefined case

2021-08-24 09:29 UTC, ThomasJuster commented on src/app/modules/group/helpers/group-code.ts
> +  if (a instanceof Duration && b instanceof Duration) return a.toString() === b.toString();
Fixed

2021-08-24 09:35 UTC, ThomasJuster commented on src/app/modules/shared-components/components/dhm-duration/dhm-duration.component.ts
> +  @Input() format: 'time' | 'seconds' = 'time';
I'm not sure it would be much clearer, I can do that anyway
Fixed

2021-08-24 09:40 UTC, ThomasJuster commented on src/app/modules/group/components/group-join-by-code/group-join-by-code.component.ts
> +  codeLifetimeDuration?: Duration;
code lifetime does not exist in code additions, only on group now
And `codeLifetimeDuration` is the control value, I renamed it to `codeLifetimeControlValue`
Fixed

2021-08-24 10:32 UTC, ThomasJuster commented on src/app/modules/shared-components/components/dhm-duration/dhm-duration.component.ts
> +@Component({
Fixed

2021-08-24 10:39 UTC, ThomasJuster commented on src/app/modules/group/components/group-join-by-code/group-join-by-code.component.ts
> +        this.codeLifetimeDuration = this.group.codeLifetime instanceof Duration
It's for the control value, null is not accepted by the input. `codeLifetimeDuration` has been renamed to `codeLifetimeControlValue`

2021-08-24 10:39 UTC, ThomasJuster commented on src/app/modules/shared-components/components/dhm-duration/dhm-duration.component.html
> +    <p class="label">D</p>
Fixed

2021-08-24 12:06 UTC, ThomasJuster commented on src/app/modules/group/helpers/group-code.ts
> +export type CodeLifetime = Duration | null;
Fixed

2021-08-24 12:09 UTC, ThomasJuster commented on src/app/modules/group/components/group-join-by-code/group-join-by-code.component.ts
> +  codeAdditions?: CodeAdditions;
Even with a `groupExt` you could still use `group` in the template
Fixed: naming of `codeAdditions`.

2021-08-24 12:09 UTC, ThomasJuster commented on src/app/modules/group/components/group-join-by-code/group-join-by-code.component.ts
> +        this.codeLifetimeDuration = this.group.codeLifetime instanceof Duration
Fixed

2021-08-24 12:12 UTC, ThomasJuster commented on src/app/modules/group/components/group-join-by-code/group-join-by-code.component.ts
> +    if (changes.group && this.group) {
Considering the current fixes, I don't think it is problematic anymore

2021-08-25 15:33 UTC, smadbe requested changes
Thanks 👍 Few comments remaining.

2021-08-25 15:33 UTC, smadbe commented on src/app/modules/shared-components/components/duration/duration.component.ts
> +  @Input() limitToTimeMax = false;
My comment about that was

> Maybe just a limitToTimeMax = false would be more clear? (with a clear comment on what we consider "time" here.

So add "a clear comment on what we consider "time" here."

2021-08-25 16:27 UTC, smadbe approved these changes
👍 
I haven't reviewed the global code structure/architecture today as it would take me too much time but I did it at my previous review 3w ago.
I trust you for having tested carefully the UI.

2021-08-25 16:28 UTC, merged