Feature/chapter user progress
France-ioi/AlgoreaFrontend pull request #621
Opened 2021-08-23 14:38 UTC by Iloveall

Fixes #448

2021-08-23 16:43 UTC, smadbe requested changes
I get that error each time I got in the progress tab of this item, I suppose this is not a normal behavior.
![Screenshot 2021-08-23 at 18 42 16](https://user-images.githubusercontent.com/1053150/130485094-d6b01e9f-8cbd-4d22-bc4d-78853b808327.png)

2021-08-30 13:29 UTC, Iloveall commented on src/app/modules/item/http-services/get-participant-progress.service.ts
> +    latestActivityAt: dateDecoder,
Fixed

2021-08-30 13:29 UTC, Iloveall commented on src/app/modules/item/http-services/get-participant-progress.service.ts
> +      title: D.string,
Fixed

2021-08-30 13:45 UTC, Iloveall commented on src/app/modules/item/pages/chapter-user-progress/chapter-user-progress.component.html
> +    <p-table class="alg-table alg-table chapter-user-progress" [columns]="columns" [value]="state.data" [loading]="state.isFetching">
Fixed

2021-08-31 12:55 UTC, Iloveall commented on src/app/modules/item/pages/chapter-user-progress/chapter-user-progress.component.html
> +                  [routerLink]="rowData | rawItemLink"
Fixed

2021-08-31 13:29 UTC, smadbe requested changes
👍 code ok.
It is a pity to have some titles truncated while the time spent, submission count and the score columns are too large. Could you fix that?
Also, left align the score as the rest.
![Screenshot 2021-08-31 at 15 27 45](https://user-images.githubusercontent.com/1053150/131510847-68e0fc6e-bc12-4d3e-9e4d-ee633facc759.png)

2021-09-01 07:16 UTC, smadbe requested changes
much better :-) great 👍 

Ah you haven't tested the user chapter view when observing a user :-( ? It seems it does not work.
![Screenshot 2021-09-01 at 09 16 03](https://user-images.githubusercontent.com/1053150/131628644-78544e72-97d9-4603-81fd-ed86e5b0d219.png)

2021-09-08 17:00 UTC, ThomasJuster commented
> much better :-) great 
> 
> Ah you haven't tested the user chapter view when observing a user :-( ? It seems it does not work.
> ![Screenshot 2021-09-01 at 09 16 03](https://user-images.githubusercontent.com/1053150/131628644-78544e72-97d9-4603-81fd-ed86e5b0d219.png)

I could not test it either, I tried to watch [this user](https://dev.algorea.org/en/#/activities/by-id/786619260741032385;path=4702,4102,902356740789159624,839024045585287566;attempId=0/details/progress/chapter) and go to a [chapter of one of his groups](https://dev.algorea.org/en/#/groups/by-id/31961217542260212;path=/details)
But the backend call responds `403: insufficient access rights`

2021-09-08 17:04 UTC, ThomasJuster reviewed
I have 2 small comments, after that it's good to go :+1:

2021-09-08 17:26 UTC, Iloveall commented on src/app/modules/item/pages/chapter-user-progress/chapter-user-progress.component.ts
> +  ];
Fixed

2021-09-08 17:37 UTC, Iloveall commented on src/app/modules/item/pages/chapter-user-progress/chapter-user-progress.component.ts
> +    if (!parentAttemptId) return; // unexpected: children have been loaded, so we are sure this item has an attempt
Fixed

2021-09-08 18:01 UTC, ThomasJuster approved these changes

2021-09-13 08:37 UTC, smadbe approved these changes
👍

2021-09-13 10:56 UTC, merged