Adds handling for empy task and course item  page
France-ioi/AlgoreaFrontend pull request #787
Opened 2021-10-22 12:03 UTC by Iloveall

## Description

Fixes #766

## Notes (out of scope, known isues, hints for reviewing code, ...)  (optional)

...

## Test cases

- [x] Case 1:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/branch/feature/do-not-let-item-page-empty/en/#/activities/by-id/2268458803184278714;path=;attempId=0/details)
  4. Then I see "This activity has not been correctly configured" and "You need to set a url in editing mode." messages
  

- [x] Case 2:
  1. Given am the usual user
  2. When I go to [this page](https://dev.algorea.org/branch/feature/do-not-let-item-page-empty/en/#/activities/by-id/4161175831988689371;path=1352246428241737349,561969155071897034;parentAttempId=0/details)
  4. Then I see Chapter with "This activity requires explicit entry (not implemented)." message

- [x] Case 3:
  1. Given am the usual user
  2. When I go to [this page](https://dev.algorea.org/branch/feature/do-not-let-item-page-empty/en/#/activities/by-id/7484937021725214233;path=1352246428241737349,561969155071897034;parentAttempId=0/details)
  4. Then I see Task with "This activity requires explicit entry (not implemented)." message
  
- [x] Case 4:
  1. Given am the user demouser
  2. When I go to [this page](https://dev.algorea.org/branch/feature/do-not-let-item-page-empty/en/#/activities/by-id/1501663083087440078;path=4702,1625159049301502151;parentAttempId=0/details)
  4. Then I see Task with "This activity has not been correctly configured." message

2021-11-28 11:53 UTC, Iloveall commented on src/app/modules/item/pages/item-content/item-content.component.html
>  <ng-container *ngIf="itemData">
Yes, we have agreement with @smadbe to improve it in next task.

2021-11-29 09:14 UTC, ThomasJuster reviewed
Good to go for me :heavy_check_mark: 
@smadbe since it's your issue … your turn :grin: 

I could also test the use case `display "Starting the activity ..."` when visiting [this chapter](https://dev.algorea.org/branch/feature/do-not-let-item-page-empty/en/#/activities/by-id/1625159049301502151;path=4702;attempId=0/details) as usual user by throttling network to bad connection like 3G
Since the result is built up -on item in datasource, this message is displayed while the item is fetched **and** the results are being fetched. As a user I would have expected a loader, but when reading the issue I understand it as the expected behavior, is it ?

2021-11-30 16:40 UTC, smadbe requested changes
* Could you merge into this branch and fix the conflict first?  As your code is pretty old, item-content has changed in between.

* This course with explicit entry should behave like others: https://dev.algorea.org/branch/feature/do-not-let-item-page-empty/en/#/activities/by-id/596025909122824879;path=1352246428241737349,561969155071897034;attempId=0/details

* Could you provide a test case of a task without url but on which the user has no editing permissions?

* as suggested by Thomas, please add a loader after the "Starting the activity ... " message.

2021-12-06 09:15 UTC, ThomasJuster reviewed
I retested and checked the loader, works fine :+1: 
I'm leaving the rest to Damien

2021-12-10 09:46 UTC, smadbe approved these changes

2021-12-10 17:36 UTC, merged