auto activate or deactivate full frame depending on item type
France-ioi/AlgoreaFrontend pull request #808
Opened 2021-11-09 14:10 UTC by ThomasJuster

## Description

Fixes #729 
Closes #779 

## Notes

This PR _might_ evolve **slightly** when [this question](https://github.com/France-ioi/AlgoreaFrontend/issues/729#issuecomment-964154553) will be addressed.

Currently, I considered that courses ought to be treated just like tasks.

## Test cases

- [ ] Case 1: 
  * When navigating to a task, **not using** the left nav for navigation
  * Then, the left menu collapses (if not already)
- [ ] Case 2:
  * When navigating to a task, **using** the left nav for navigation
  * Then, the left menu stays visible
- [ ] Case 3:
  * When navigating to a non-task (chapter, skill, group, ...) from a task 
  * Then, the left menu expends (if not already)
- [ ] Case 4:
  * When navigating to a non-task (chapter, skill, group, ...) from a non-task 
  * Then, the left menu stays as it was
- [ ] Case 5:
  * When using the collapse/expend button on the top of the left menu
  * Then, the left menu collapses/expends as expected

2021-11-09 21:21 UTC, smadbe requested changes
A case which does not respect
>  When navigating to a non-task (chapter, skill, group, ...) from a non-task
>  Then, the left menu stays as it was

- I visit a [chapter](https://dev.algorea.org/branch/feat/task-full-frame/en/#/activities/by-id/34689573454313988;path=4702,1352246428241737349,314613032161178344;attempId=0/details)
- I manually collapse the menu
- Then I visit the parent through the header.
- I would expect "the left menu stays as it was", but it auto-expends

2021-11-15 09:02 UTC, smadbe approved these changes

2021-11-15 10:03 UTC, ThomasJuster commented on src/app/core/services/navigation/item-nav-tree.service.ts
> +      navigateTo: (_path: string[], preventFullFrame = false): void => this.itemRouter.navigateTo(contentInfo.route, { preventFullFrame }),
At first I thought the same :smile:, actually this is not exactly the left menu now, it's also used by the item-header

2021-11-15 11:24 UTC, ThomasJuster commented on src/app/modules/item/pages/item-by-id/item-by-id.component.ts
> +        filter(isNotUndefined),
fixed

2021-11-15 11:24 UTC, ThomasJuster commented on src/app/modules/item/pages/item-by-id/item-by-id.component.ts
> +        filter(([ previous, current ]) => !previous || isTask(previous.item) || !current || isTask(current?.item)),
fixed

2021-11-15 11:24 UTC, merged