Subgroup switch
France-ioi/AlgoreaFrontend pull request #88
Opened 2020-09-18 09:37 UTC by AyeRlS

Adding the switch "group only / all subgroups".

2020-09-18 13:00 UTC, smadbe requested changes
👍 
Few details to be changed.

2020-09-18 14:13 UTC, AyeRlS commented on src/app/modules/group/components/pending-request/pending-request.component.ts
> +  onSwitchChange(isAllowed: number)
implemented !

2020-09-18 14:13 UTC, AyeRlS commented on src/app/modules/group/components/pending-request/pending-request.component.ts
> +  ];
done

2020-09-18 18:31 UTC, smadbe commented on src/app/modules/group/components/pending-request/pending-request.component.ts
> +  ];
When there is a suggestion, you can just "commit suggestion" as well

2020-09-21 07:46 UTC, smadbe approved these changes

2020-09-21 09:13 UTC, merged