Updates primeng
France-ioi/AlgoreaFrontend pull request #900
Opened 2022-02-08 16:33 UTC by Iloveall

## Description

Fixes #...

## Notes (out of scope, known isues, hints for reviewing code, ...)  (optional)

https://github.com/primefaces/primeng/wiki/Migration-Guide

Need to re-install node packages

## Test cases

- [ ] Case 1:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/branch/feature/prime-ng-update/en/#/groups/mine)
  3. Then I see 2 type of tables without design changes

- [ ] Case 2:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/en/#/groups/by-id/672913018859223173;path=52767158366271444/details)
  3. Click on Activities tab then Parcours officiels -> Parcours officiels -> L1S1 Computer science
  4. Then click on Chapter View tab -> users
  5. Then I see table without design changes

2022-02-09 10:14 UTC, ThomasJuster requested changes

2022-02-09 10:14 UTC, ThomasJuster commented on package.json
>      "jschannel": "^1.0.2",
I found a UI regression [here](https://dev.algorea.org/branch/feature/prime-ng-update/en/#/groups/by-id/609422240375608067;path=/details/managers) as usual user:
![image](https://user-images.githubusercontent.com/16257159/153176185-31a4f927-4c90-4d56-ba47-f2487feae5db.png)

2022-02-09 10:14 UTC, ThomasJuster commented on package.json
>      "jschannel": "^1.0.2",
Still scroll problems, I think they are all related so I'll stop the review here
When watching [Super group of mine (Thomas)](https://dev.algorea.org/branch/feature/prime-ng-update/en/#/groups/by-id/6710944276987033666;path=52767158366271444,672913018859223173/details) and navigating to suggested activity "Blockly basic task" / Progress / Chapter view:

![image](https://user-images.githubusercontent.com/16257159/153177403-32064c5f-6f95-4ed5-ac5b-edd4b1aaa4b0.png)

2022-02-09 16:57 UTC, ThomasJuster commented on package.json
>      "jschannel": "^1.0.2",
Resolving comment because it's the current behavior in production and is not related to this PR

2022-02-09 17:14 UTC, ThomasJuster commented on package.json
>      "jschannel": "^1.0.2",
Duplicat of #901

2022-02-09 17:35 UTC, Iloveall commented on package.json
>      "jschannel": "^1.0.2",
Fixed

2022-02-10 09:48 UTC, ThomasJuster reviewed
All good for me :heavy_check_mark: 
@smadbe you want to take a look ?

2022-02-11 12:23 UTC, smadbe commented
I'll assume you have tested carefully most of screen, I have not much to test that you cannot do.

2022-02-11 12:52 UTC, smadbe approved these changes

2022-02-11 12:52 UTC, merged